# Generated by Django 6.0.3 on 2026-03-13 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentGradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_number', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('grade_threshold', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ExamBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GradeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2026)])),
                ('grade', models.CharField(max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('num_students', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='DocumentURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('past_paper', 'Past Paper'), ('mark_scheme', 'Mark Scheme'), ('exam_report', 'Exam Report')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_data.componentgradeboundary')),
            ],
        ),
        migrations.CreateModel(
            name='OverallGradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2026)])),
                ('grade', models.CharField(max_length=10)),
                ('grade_threshold', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('exam_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_data.examboard')),
            ],
        ),
        migrations.AddField(
            model_name='componentgradeboundary',
            name='overall_grade_boundary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_data.overallgradeboundary'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_data.examboard')),
            ],
        ),
        migrations.AddField(
            model_name='overallgradeboundary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_data.subject'),
        ),
    ]
