# Generated by Django 6.0.3 on 2026-03-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overallgradeboundary',
            name='exam_board',
        ),
        migrations.AddField(
            model_name='gradestatistic',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_data.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examboard',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='componentgradeboundary',
            index=models.Index(fields=['overall_grade_boundary', 'paper_number'], name='exam_data_c_overall_1e1d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='documenturl',
            index=models.Index(fields=['paper', 'document_type'], name='exam_data_d_paper_i_45b1db_idx'),
        ),
        migrations.AddIndex(
            model_name='gradestatistic',
            index=models.Index(fields=['subject', 'year'], name='exam_data_g_subject_f436da_idx'),
        ),
        migrations.AddIndex(
            model_name='overallgradeboundary',
            index=models.Index(fields=['subject', 'year'], name='exam_data_o_subject_279f57_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['exam_board'], name='exam_data_s_exam_bo_2b3eb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentgradeboundary',
            constraint=models.UniqueConstraint(fields=('overall_grade_boundary', 'paper_number', 'grade'), name='unique_component_boundary'),
        ),
        migrations.AddConstraint(
            model_name='overallgradeboundary',
            constraint=models.UniqueConstraint(fields=('subject', 'year', 'grade'), name='unique_boundary'),
        ),
    ]
