# Generated by Django 6.0.3 on 2026-04-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_data', '0002_remove_overallgradeboundary_exam_board_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gradestatistic',
            constraint=models.UniqueConstraint(fields=('subject', 'year', 'grade'), name='unique_statistic'),
        ),
    ]
