# Generated by Django 6.0.3 on 2026-04-21 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_data', '0003_gradestatistic_unique_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2026)])),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='componentgradeboundary',
            name='unique_component_boundary',
        ),
        migrations.RemoveConstraint(
            model_name='gradestatistic',
            name='unique_statistic',
        ),
        migrations.RemoveConstraint(
            model_name='overallgradeboundary',
            name='unique_boundary',
        ),
        migrations.RemoveIndex(
            model_name='componentgradeboundary',
            name='exam_data_c_overall_1e1d6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='gradestatistic',
            name='exam_data_g_subject_f436da_idx',
        ),
        migrations.RemoveIndex(
            model_name='overallgradeboundary',
            name='exam_data_o_subject_279f57_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='exam_data_s_exam_bo_2b3eb3_idx',
        ),
        migrations.AlterField(
            model_name='examboard',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['exam_board', 'name'], name='exam_data_s_exam_bo_e92397_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('exam_board', 'name'), name='unique_subject'),
        ),
        migrations.AddField(
            model_name='componentgradeboundary',
            name='exam_paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_data.exampaper'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenturl',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_data.exampaper'),
        ),
        migrations.AddIndex(
            model_name='componentgradeboundary',
            index=models.Index(fields=['exam_paper'], name='exam_data_c_exam_pa_8f6f9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentgradeboundary',
            constraint=models.UniqueConstraint(fields=('exam_paper', 'grade'), name='unique_component_boundary'),
        ),
        migrations.AddConstraint(
            model_name='documenturl',
            constraint=models.UniqueConstraint(fields=('paper', 'document_type'), name='unique_doc'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_data.subject'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_data.examsession'),
        ),
        migrations.AddField(
            model_name='gradestatistic',
            name='exam_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_data.examsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overallgradeboundary',
            name='exam_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_data.examsession'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gradestatistic',
            index=models.Index(fields=['exam_session'], name='exam_data_g_exam_se_66d298_idx'),
        ),
        migrations.AddIndex(
            model_name='overallgradeboundary',
            index=models.Index(fields=['exam_session'], name='exam_data_o_exam_se_546429_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradestatistic',
            constraint=models.UniqueConstraint(fields=('exam_session', 'grade'), name='unique_statistic'),
        ),
        migrations.AddConstraint(
            model_name='overallgradeboundary',
            constraint=models.UniqueConstraint(fields=('exam_session', 'grade'), name='unique_boundary'),
        ),
        migrations.RemoveField(
            model_name='componentgradeboundary',
            name='overall_grade_boundary',
        ),
        migrations.RemoveField(
            model_name='componentgradeboundary',
            name='paper_number',
        ),
        migrations.RemoveField(
            model_name='gradestatistic',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='gradestatistic',
            name='year',
        ),
        migrations.RemoveField(
            model_name='overallgradeboundary',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='overallgradeboundary',
            name='year',
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['subject', 'year'], name='exam_data_e_subject_29e3a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(fields=('subject', 'year'), name='unique_exam'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['exam_session'], name='exam_data_e_exam_se_41b676_idx'),
        ),
        migrations.AddConstraint(
            model_name='exampaper',
            constraint=models.UniqueConstraint(fields=('exam_session', 'paper_number'), name='unique_paper'),
        ),
    ]
