# Generated by Django 6.0.3 on 2026-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_data', '0004_exampaper_examsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenturl',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
